import { PickupOrder, PickupReturn, StationStaff } from './types';

export const initialOrders: PickupOrder[] = [
  {
    id: 'pkg-1',
    orderId: 'ORD-1002',
    packageId: 'PKG-1002-A',
    customerName: 'Aisha Omar',
    customerPhone: '+255 712 345 678',
    sellerName: 'Kariakoo Electronics',
    deliveryType: 'STANDARD',
    status: 'INCOMING',
    arrivalStatus: 'PENDING',
    packageCount: 1,
    paymentStatus: 'PAID',
    amountDue: 0,
  },
  {
    id: 'pkg-2',
    orderId: 'ORD-1005',
    packageId: 'PKG-1005-B',
    customerName: 'Brian Kimario',
    customerPhone: '+255 754 999 888',
    sellerName: 'Fashion Hub',
    deliveryType: 'EXPRESS',
    status: 'RECEIVED',
    arrivalStatus: 'ARRIVED',
    arrivedAt: new Date().toISOString(),
    packageCount: 2,
    paymentStatus: 'CASH_ON_PICKUP',
    amountDue: 45000,
  },
  {
    id: 'pkg-3',
    orderId: 'ORD-0998',
    packageId: 'PKG-0998-A',
    customerName: 'Fatma Juma',
    customerPhone: '+255 788 111 222',
    sellerName: 'Home Essentials',
    deliveryType: 'STANDARD',
    status: 'STORED',
    arrivalStatus: 'ARRIVED',
    arrivedAt: new Date(Date.now() - 3600000).toISOString(),
    shelfLocation: 'A-02-14',
    packageCount: 1,
    paymentStatus: 'PAID',
    amountDue: 0,
  },
  {
    id: 'pkg-4',
    orderId: 'ORD-0950',
    packageId: 'PKG-0950-A',
    customerName: 'Daniel Mrosso',
    customerPhone: '+255 766 555 444',
    sellerName: 'Tech Store TZ',
    deliveryType: 'EXPRESS',
    status: 'READY',
    arrivalStatus: 'ARRIVED',
    arrivedAt: new Date(Date.now() - 86400000).toISOString(),
    pickupDeadline: new Date(Date.now() + 172800000).toISOString(),
    shelfLocation: 'B-01-05',
    pickupOtpCode: '8241',
    packageCount: 1,
    paymentStatus: 'PAID',
    amountDue: 0,
  },
  {
    id: 'pkg-5',
    orderId: 'ORD-0800',
    packageId: 'PKG-0800-C',
    customerName: 'Sarah Temba',
    customerPhone: '+255 744 333 222',
    sellerName: 'Beauty Cosmetics',
    deliveryType: 'STANDARD',
    status: 'NOTIFIED',
    arrivalStatus: 'ARRIVED',
    arrivedAt: new Date(Date.now() - 259200000).toISOString(),
    pickupDeadline: new Date(Date.now() + 86400000).toISOString(),
    shelfLocation: 'C-04-12',
    pickupOtpCode: '1945',
    packageCount: 3,
    paymentStatus: 'PENDING',
    amountDue: 15000,
  },
  {
    id: 'pkg-6',
    orderId: 'ORD-0750',
    packageId: 'PKG-0750-A',
    customerName: 'Emmanuel Lyimo',
    customerPhone: '+255 711 222 333',
    sellerName: 'Sports Gear Ltd',
    deliveryType: 'STANDARD',
    status: 'EXPIRED',
    arrivalStatus: 'ARRIVED',
    arrivedAt: new Date(Date.now() - 604800000).toISOString(),
    pickupDeadline: new Date(Date.now() - 86400000).toISOString(),
    shelfLocation: 'D-01-01',
    packageCount: 1,
    paymentStatus: 'PAID',
    amountDue: 0,
  }
];

export const initialReturns: PickupReturn[] = [
  {
    id: 'ret-1',
    orderId: 'ORD-0600',
    customerName: 'Grace Mollel',
    productName: 'Samsung Galaxy A32',
    reason: 'Defective screen',
    condition: 'Open Box - Damaged',
    status: 'REQUESTED',
    createdAt: new Date().toISOString()
  }
];

export const initialStaff: StationStaff[] = [
  { id: 'stf-1', name: 'Baraka M.', role: 'Manager', shift: 'Morning (08:00 - 16:00)', status: 'Active' },
  { id: 'stf-2', name: 'Joyce N.', role: 'Pickup Staff', shift: 'Morning (08:00 - 16:00)', status: 'Active', currentTask: 'Customer Handover (ORD-0950)' },
  { id: 'stf-3', name: 'Peter S.', role: 'Returns Staff', shift: 'Morning (08:00 - 16:00)', status: 'Available' },
  { id: 'stf-4', name: 'Salum K.', role: 'Cashier', shift: 'Evening (14:00 - 22:00)', status: 'Offline' }
];
